export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_TOKEN = 'INVALID_TOKEN',
  AGENT_NOT_FOUND = 'AGENT_NOT_FOUND',
  AGENT_DEACTIVATED = 'AGENT_DEACTIVATED',
  DID_ALREADY_REGISTERED = 'DID_ALREADY_REGISTERED',
  CREDENTIAL_NOT_FOUND = 'CREDENTIAL_NOT_FOUND',
  CREDENTIAL_EXPIRED = 'CREDENTIAL_EXPIRED',
  CREDENTIAL_REVOKED = 'CREDENTIAL_REVOKED',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  SESSION_NOT_ACTIVE = 'SESSION_NOT_ACTIVE',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  INVALID_TURN = 'INVALID_TURN',
  NOT_YOUR_TURN = 'NOT_YOUR_TURN',
  MAX_TURNS_REACHED = 'MAX_TURNS_REACHED',
  PROOF_GENERATION_FAILED = 'PROOF_GENERATION_FAILED',
  PROOF_VERIFICATION_FAILED = 'PROOF_VERIFICATION_FAILED',
  CIRCUIT_NOT_FOUND = 'CIRCUIT_NOT_FOUND',
  COMMITMENT_NOT_FOUND = 'COMMITMENT_NOT_FOUND',
  COMMITMENT_ALREADY_EXISTS = 'COMMITMENT_ALREADY_EXISTS',
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
  RPC_ERROR = 'RPC_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}

export class AttestaraError extends Error {
  constructor(
    public readonly code: ErrorCode,
    message: string,
    public readonly details?: Record<string, unknown> | undefined,
  ) {
    super(message)
    this.name = 'AttestaraError'
  }
}
